"""
Demo seed data — 20 hand-crafted meme entries with realistic metadata.
Loaded automatically when the local index is empty (data pipeline not yet run).
Each meme uses real publicly-available Imgflip image URLs.
"""

DEMO_MEMES = [
    {
        "id": "demo_drake",
        "name": "Drake Pointing",
        "slug": "drake-pointing",
        "category": "reaction",
        "categories": ["reaction", "comparison", "funny"],
        "emotions": ["humor", "joy", "sarcasm"],
        "keywords": ["drake", "no yes", "prefer", "better", "choose"],
        "dialogue": "Disapproving of one thing vs strongly approving of another",
        "explanation": "Drake Hotline Bling format — rejecting an option on top, preferring another below.",
        "image_url": "https://i.imgflip.com/30b1gx.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.95,
        "usage_count": 50000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_distracted_bf",
        "name": "Distracted Boyfriend",
        "slug": "distracted-boyfriend",
        "category": "reaction",
        "categories": ["reaction", "comparison", "relatable"],
        "emotions": ["humor", "surprise", "joy"],
        "keywords": ["distracted", "girlfriend", "new thing", "tempted", "looking"],
        "dialogue": "When you're supposed to focus on one thing but get distracted by another",
        "explanation": "Man looking back at another woman while walking with his girlfriend — classic comparison meme.",
        "image_url": "https://i.imgflip.com/1ur9b0.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.92,
        "usage_count": 45000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_this_is_fine",
        "name": "This Is Fine Dog",
        "slug": "this-is-fine",
        "category": "reaction",
        "categories": ["reaction", "relatable", "coding", "work"],
        "emotions": ["sadness", "humor", "frustration", "neutral"],
        "keywords": ["fine", "burning", "chaos", "calm", "disaster", "okay"],
        "dialogue": "Everything is on fire but acting like it's totally fine",
        "explanation": "Dog sitting in burning room with coffee mug saying 'This is fine.' Perfect for when everything is falling apart.",
        "image_url": "https://i.imgflip.com/wxica.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.91,
        "usage_count": 42000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_two_buttons",
        "name": "Two Buttons",
        "slug": "two-buttons",
        "category": "reaction",
        "categories": ["reaction", "comparison", "work", "coding"],
        "emotions": ["anxiety", "frustration", "humor"],
        "keywords": ["two buttons", "choice", "dilemma", "sweat", "decision"],
        "dialogue": "Facing an impossible choice between two equally bad options",
        "explanation": "Man sweating over which button to press — for when you can't decide between two options.",
        "image_url": "https://i.imgflip.com/1g8my4.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.88,
        "usage_count": 38000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_gru_plan",
        "name": "Gru's Plan",
        "slug": "grus-plan",
        "category": "reaction",
        "categories": ["reaction", "relatable", "coding", "failure"],
        "emotions": ["humor", "surprise", "frustration"],
        "keywords": ["plan", "step", "same", "backfire", "oops", "gru"],
        "dialogue": "A 4-panel plan where the last step is identical to a step you wanted to avoid",
        "explanation": "Gru from Despicable Me explaining his plan — the last panel reveals he's also affected by it.",
        "image_url": "https://i.imgflip.com/26am.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.87,
        "usage_count": 35000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_always_has_been",
        "name": "Always Has Been",
        "slug": "always-has-been",
        "category": "reaction",
        "categories": ["reaction", "wholesome", "funny"],
        "emotions": ["surprise", "humor"],
        "keywords": ["always has been", "wait", "whole time", "astronaut", "revelation"],
        "dialogue": "Realizing something has always been true, usually ironically",
        "explanation": "Two astronauts on the moon — one realizes something shocking and the other reveals it was always that way.",
        "image_url": "https://i.imgflip.com/489taf.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.83,
        "usage_count": 29000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_uno_reverse",
        "name": "UNO Reverse Card",
        "slug": "uno-reverse-card",
        "category": "reaction",
        "categories": ["reaction", "funny", "relationship"],
        "emotions": ["humor", "joy", "sarcasm"],
        "keywords": ["uno", "reverse", "no u", "comeback", "turnabout"],
        "dialogue": "Turning someone's argument back on them",
        "explanation": "The UNO reverse card — for epic comebacks and turning situations around.",
        "image_url": "https://i.imgflip.com/3lmzyx.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.81,
        "usage_count": 26000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_bernie_mittens",
        "name": "Bernie Sanders Mittens",
        "slug": "bernie-sanders-mittens",
        "category": "reaction",
        "categories": ["reaction", "wholesome", "funny"],
        "emotions": ["humor", "neutral", "joy"],
        "keywords": ["bernie", "mittens", "sitting", "watching", "unbothered", "here"],
        "dialogue": "Bernie Sanders unbothered, just sitting there watching things unfold",
        "explanation": "Bernie Sanders sitting with mittens — photoshopped into various scenes for commentary.",
        "image_url": "https://i.imgflip.com/4r1yt0.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.78,
        "usage_count": 22000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_change_my_mind",
        "name": "Change My Mind",
        "slug": "change-my-mind",
        "category": "advice",
        "categories": ["advice", "reaction", "funny"],
        "emotions": ["humor", "neutral", "frustration"],
        "keywords": ["change my mind", "table", "opinion", "debate", "crowder"],
        "dialogue": "Stating an opinion and daring someone to prove you wrong",
        "explanation": "Steven Crowder at a table saying 'Change My Mind.' Use for stating hot takes.",
        "image_url": "https://i.imgflip.com/24y43o.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.82,
        "usage_count": 27000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_expanding_brain",
        "name": "Expanding Brain",
        "slug": "expanding-brain",
        "category": "comparison",
        "categories": ["comparison", "relatable", "coding", "funny"],
        "emotions": ["humor", "joy", "surprise"],
        "keywords": ["brain", "expanding", "enlightened", "smart", "big brain", "genius"],
        "dialogue": "Escalating levels of sophistication — from basic to galaxy-brained",
        "explanation": "Brain expanding through panels — from small boring idea to absurdly grand conclusion.",
        "image_url": "https://i.imgflip.com/1jwhww.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.85,
        "usage_count": 32000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_mocking_spongebob",
        "name": "Mocking SpongeBob",
        "slug": "mocking-spongebob",
        "category": "reaction",
        "categories": ["reaction", "funny", "sarcasm"],
        "emotions": ["humor", "sarcasm", "frustration"],
        "keywords": ["mocking", "spongebob", "alternating caps", "sarcasm", "like that"],
        "dialogue": "Sarcastically repeating someone with alternating caps to mock them",
        "explanation": "SpongeBob in a weird pose — used to mockingly repeat someone's statement.",
        "image_url": "https://i.imgflip.com/1otk96.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.84,
        "usage_count": 30000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_hide_the_pain_harold",
        "name": "Hide the Pain Harold",
        "slug": "hide-the-pain-harold",
        "category": "reaction",
        "categories": ["reaction", "relatable", "work", "coding"],
        "emotions": ["sadness", "frustration", "humor", "neutral"],
        "keywords": ["pain", "harold", "smiling", "hiding", "pretend", "fine", "suffering"],
        "dialogue": "Smiling on the outside while suffering on the inside",
        "explanation": "András Arató smiling while clearly in pain — for hidden suffering and forced cheerfulness.",
        "image_url": "https://i.imgflip.com/gk5el.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.86,
        "usage_count": 33000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_one_does_not_simply",
        "name": "One Does Not Simply",
        "slug": "one-does-not-simply",
        "category": "advice",
        "categories": ["advice", "funny", "relatable"],
        "emotions": ["humor", "frustration", "neutral"],
        "keywords": ["one does not simply", "boromir", "lord of the rings", "walk into"],
        "dialogue": "One does not simply [do an obviously difficult thing]",
        "explanation": "Boromir from LOTR — for things that sound simple but absolutely aren't.",
        "image_url": "https://i.imgflip.com/1bij.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.80,
        "usage_count": 24000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_success_kid",
        "name": "Success Kid",
        "slug": "success-kid",
        "category": "achievement",
        "categories": ["achievement", "wholesome", "funny"],
        "emotions": ["joy", "pride", "surprise"],
        "keywords": ["success", "fist", "win", "finally", "yes", "achievement"],
        "dialogue": "Finally achieved something after a long struggle",
        "explanation": "Baby with fist pump — the gold standard for celebrating small or big wins.",
        "image_url": "https://i.imgflip.com/1bhf.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.79,
        "usage_count": 21000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_y_u_no",
        "name": "Y U No Guy",
        "slug": "y-u-no",
        "category": "reaction",
        "categories": ["reaction", "frustration", "funny"],
        "emotions": ["anger", "frustration", "humor"],
        "keywords": ["why", "you no", "why not", "frustrated", "angry", "complain"],
        "dialogue": "Aggressively asking why someone won't do something obvious",
        "explanation": "Rage face demanding explanations. For frustration at things that should be simple.",
        "image_url": "https://i.imgflip.com/1bip.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.72,
        "usage_count": 15000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_waiting_skeleton",
        "name": "Waiting Skeleton",
        "slug": "waiting-skeleton",
        "category": "reaction",
        "categories": ["reaction", "relatable", "work", "funny"],
        "emotions": ["frustration", "sadness", "neutral", "humor"],
        "keywords": ["waiting", "skeleton", "forever", "still", "long time", "patience"],
        "dialogue": "Still waiting for something that was promised long ago",
        "explanation": "Skeleton waiting at a table — for things that take absurdly long.",
        "image_url": "https://i.imgflip.com/2fm6x.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.74,
        "usage_count": 17000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_surprised_pikachu",
        "name": "Surprised Pikachu",
        "slug": "surprised-pikachu",
        "category": "reaction",
        "categories": ["reaction", "funny", "gaming"],
        "emotions": ["surprise", "humor"],
        "keywords": ["pikachu", "surprised", "shocked", "didn't expect", "wow"],
        "dialogue": "Being shocked by a totally predictable outcome",
        "explanation": "Surprised Pikachu face — for when something obvious happens but you're still shocked.",
        "image_url": "https://i.imgflip.com/3c7pde.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.89,
        "usage_count": 40000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_monkey_puppet",
        "name": "Monkey Looking Away",
        "slug": "monkey-looking-away",
        "category": "reaction",
        "categories": ["reaction", "funny", "relatable"],
        "emotions": ["humor", "neutral", "frustration"],
        "keywords": ["monkey", "looking away", "awkward", "uncomfortable", "avoid", "ignore"],
        "dialogue": "Awkwardly looking away from an uncomfortable truth or situation",
        "explanation": "Puppet monkey turning to look, then looking away — for awkward moments and avoidance.",
        "image_url": "https://i.imgflip.com/4t0m5.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.83,
        "usage_count": 28000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_panik_kalm",
        "name": "Panik Kalm Panik",
        "slug": "panik-kalm-panik",
        "category": "reaction",
        "categories": ["reaction", "relatable", "coding", "work", "funny"],
        "emotions": ["anxiety", "fear", "humor", "relief"],
        "keywords": ["panik", "kalm", "panic", "calm", "relax", "worry", "oh no", "wait"],
        "dialogue": "Panic — realize something — calm briefly — realize something worse — panic again",
        "explanation": "Three-panel panik/kalm meme. Perfect for escalating realizations.",
        "image_url": "https://i.imgflip.com/3nyb7q.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.86,
        "usage_count": 34000,
        "nsfw": False,
        "source": "imgflip",
    },
    {
        "id": "demo_math_lady",
        "name": "Confused Math Lady",
        "slug": "confused-math-lady",
        "category": "reaction",
        "categories": ["reaction", "relatable", "coding", "funny"],
        "emotions": ["confusion", "frustration", "humor"],
        "keywords": ["confused", "math", "calculations", "thinking", "brain", "numbers"],
        "dialogue": "Trying to figure out something that's making your brain hurt",
        "explanation": "Woman with math equations floating around her head — for when you're completely baffled.",
        "image_url": "https://i.imgflip.com/1otk96.jpg",
        "gif_url": None,
        "has_gif": False,
        "has_video": False,
        "popularity_score": 0.77,
        "usage_count": 20000,
        "nsfw": False,
        "source": "imgflip",
    },
]
